---
abstract: 'PDF generator for HTML templates'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  CAM::PDF: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Flute-PDF
no_index:
  directory:
    - t
    - inc
requires:
  Image::Size: 0
  PDF::API2: 0
  Template::Flute: 0.0025
  Template::Flute::Style::CSS: 0.003
version: 0.0040
