--- #YAML:1.0
name:               Template-Flute-PDF
version:            0.0025
abstract:           PDF generator for HTML templates
author:
    - Stefan Hornburg (Racke) <racke@linuxia.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    CAM::PDF:    0
    Test::More:  0
requires:
    Image::Magick:        0
    Image::Size:          0
    PDF::API2:            0
    Template::Flute:      0
    Template::Flute::Style::CSS:  0.0025
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
